### ISSUE TITLE
Syntax highlight on jsx attributes

### ISSUE THREAD

**Issue by yemi** [subtleGradient/language-javascript-jsx#1]
First of all, thank you for this package, I haven't found any other package that adds syntax highlighting for jsx AND es6, so thanks..

There is probably only one thing that im missing currently and that is highlighting on attributes on jsx elements.

Currently it looks like this and it gets a little messy after a while.
![screen shot 2014-11-29 at 11 19 38](https://cloud.githubusercontent.com/assets/416424/5234159/e1b15ec4-77b9-11e4-8af3-d5430f66dba4.png)

**Comment by subtleGradient** [comment]
This should be technically working properly, assuming your theme supports it at least.
Please let me know if there's anything else broken.

Thanks much!
