### ISSUE TITLE
syntax problems for quotes in HTML comments

### ISSUE THREAD

**Issue by giorgian** [subtleGradient/language-javascript-jsx#2]
With this package enabled, a quote (both single and double) in an HTML comment breaks syntax highlighting for the rest of the buffer.

![screencast]
(http://g.recordit.co/6U502fVQQH.gif)

**Comment by jzumbrun** [comment]
This issue also affects php comments not just html comments. I had to disable this plugin it is such an annoying issue.

**Comment by subtleGradient** [comment]
Oh crap. Sorry about that

**Comment by subtleGradient** [comment]
Oh dang. I don't know how I missed this issue for this long. I need to get better at email or something. Thanks for providing such an awesome bug report with animations and everything!

I'll try to get this fixed asap. Sorry for the delay

**Comment by subtleGradient** [comment]
This grammar was converted from my TextMate 2 language syntax. Looks like Atom doesn't support all the scope rules that TextMate 2 supports. I'll just disable the JSX in HTML SCRIPT tags for Atom until I can come up with a way to convince Atom to let me do it properly

**Comment by subtleGradient** [comment]
v0.3.2 should fix this.
Sorry again :[

**Comment by jzumbrun** [comment]
Works, fixed thanks!
