### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by saidmoya12** [subtleGradient/language-javascript-jsx#20]
undetected close tag />

<div>
    <div/>
</div>

**Comment by Macil** [comment]
Is this an error you get?

**Comment by DennisBecker** [comment]
This is a highlighting issue - when using a React Component without children it does not match the closing tag /> and everything below this looks broken. It would be nice if you could fix this issue.

<img width="902" alt="screen shot 2017-01-25 at 09 43 47" src="https://cloud.githubusercontent.com/assets/66930/22283499/dd308b2c-e2e2-11e6-8b7b-82ad6e3a98d7.png">

**Comment by TinkGu** [comment]
I have a same problem. @subtleGradient . It would be nice if you could fix this issue, thank you!
