### ISSUE TITLE
Package is messing with PHP formatting

### ISSUE THREAD

**Issue by FaridW** [subtleGradient/language-javascript-jsx#3]
I initially assumed this bug to be related to the PHP formatter built into Atom, but after some trial and error I tracked it down to this package instead.

See original issue I posted [here](https://github.com/atom/language-php/issues/68).

This is one code example that triggers the issue (extracted from a .php file):

```php
// Set address name if it wasn't entered
if (!$location->getAddressOne() && $location->getAddressTwo())
{
	$location->setAddressOne($location->getAddressTwo() ? ' ' . $location->getAddressTwo() : '');
}

$hasAddress = $location->getAddressOne() ? true : false;
```

Changing the first line of the code to remove the apostrophe corrects the problem:

```php
// Set address name if it wasnt entered
if (!$location->getAddressOne() && $location->getAddressTwo())
{
	$location->setAddressOne($location->getAddressTwo() ? ' ' . $location->getAddressTwo() : '');
}

$hasAddress = $location->getAddressOne() ? true : false;
```

**Comment by subtleGradient** [comment]
Fixed in v0.3.2
Sorry :[
