### ISSUE TITLE
Remove name in Langauage status bar

### ISSUE THREAD

**Issue by damassi** [subtleGradient/language-javascript-jsx#5]
I know this is pretty nitpicky, and people like credit, but seeing "Javascript by SubtleGradient" in my status bar is super annoying. Is it possible to change that to something more subtle like "Javascript+"? It also takes up a ton of space.

![c77b5cc6-1c0f-11e5-9b91-857ae7b2123a](https://cloud.githubusercontent.com/assets/236943/8388822/3d7eb36c-1c1c-11e5-8835-ad5134d8ddba.png)

Some suggestions:  Since you're covering all the bases (React, ES6/7, etc) how about JavaScriptNext? Or JavaScriptHarmony? Understandably both those terms seem a bit dated, but they do seem appropriate.

**Comment by tfausak** [comment]
:+1: I would also like to see something like "JavaScript+". It would be an easy change to make here: https://github.com/subtleGradient/language-javascript-jsx/blob/v0.3.7/grammars/javascript.cson#L1

**Comment by damassi** [comment]
@tfausak - I've found that by switching to Language Babel all issues are fixed, you get JSX for free, and the syntax highlighter is more wide ranging

**Comment by tfausak** [comment]
Thanks for the suggestion! The [language-babel](https://atom.io/packages/language-babel) package looks nice.
