### ISSUE TITLE
Treat 'let' as keyword

### ISSUE THREAD

**Issue by joemcbride** [subtleGradient/language-javascript-jsx#6]
Currently the `let` keyword doesn't get tagged as a keyword and gets lost in the mix.  Is this something you are able to fix?  Thanks!

![image](https://cloud.githubusercontent.com/assets/255007/8626323/25f6172a-26f9-11e5-9374-37462254adc4.png)

**Comment by joemcbride** [comment]
Possibly [here](https://github.com/subtleGradient/language-javascript-jsx/blob/master/grammars/javascript.cson#L715) or [here](https://github.com/subtleGradient/language-javascript-jsx/blob/master/grammars/javascript.cson#L719)?

**Comment by subtleGradient** [comment]
Pull requests welcome. But I'll try and get to this soon. Thanks for letting me know

**Comment by subtleGradient** [comment]
Just merged a PR that adds this.  Sorry for the delay
